### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by JeromSar** [NotchCraft-Servers/NotchCraft#1]
@buildcarter8 
Hello,

It has come to my attention that this repository contains copyrighted material in violation of its provided license.
The material in question is released under the TotalFreedom General License (TFGL) Version 1.0 or Version 2.0 depending on the time infringing material was introduced to this repository.

Copyrighted material included in this repository violates its license due to one or more of the following:

Redistributions of the material do not retain its copyright license in its exact form.
The original authors of this software have been misrepresented or not reprepresented at all in one or more of the following locations:
plugin.yml under authors
README.md
TFM_Util.java under DEVELOPERS
Redistributions of the material in question are available in non-source, object, packaged or compiled form.
In order to comply with the infringed material's license and its copyright restrictions, please either:
a) Remove the copyrighted material from this repository; or
b) Edit or adjust the required source files as necessary to comply with TFGL.

I hope to have properly and sufficiently informed you of the violations in this repository. If you have any further questions, don't hesitate to contact me.

Thanks in advance,
Jerom

**Comment by buildcarter8** [comment]
K Gimmie the items

**Comment by buildcarter8** [comment]
like what java files

**Comment by JeromSar** [comment]
@buildcarter8 Currently, I see the following violations:
* https://github.com/NotchCraft-Servers/NotchCraft/blob/master/src/me/buildcarter8/NotchCraft/Notchcraft.java
* https://github.com/NotchCraft-Servers/NotchCraft/blob/master/src/me/buildcarter8/NotchCraft/Commands/CantFindPlayerException.java
* https://github.com/NotchCraft-Servers/NotchCraft/blob/master/src/me/buildcarter8/NotchCraft/Commands/NC_Command.java

Thanks in advance!

**Comment by buildcarter8** [comment]
I add the same thing i added with projectx?

**Comment by buildcarter8** [comment]
This should be fixed now

**Comment by buildcarter8** [comment]
If everything is ok i will close it

**Comment by buildcarter8** [comment]
Complete

**Comment by buildcarter8** [comment]
ill leave it unlocked for any other comments

**Comment by JeromSar** [comment]
@buildcarter8 That's great, thanks!
